<a href="https://colab.research.google.com/github/yoradzasky/2025-AI-TI1B/blob/main/Jobsheet_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 4 PENGOLAHAN DATA MENGGUNAKAN PANDAS

## 1.	Membaca berbagai format file menggunakan Pandas

### a. Membaca file CSV

In [1]:
import pandas as pd

df = pd.read_csv('./data.csv')
print(df.to_string ())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [2]:
import pandas as pd
df
pd.options.display.max_rows
pd.options.display.max_rows = 9999

df = pd.read_csv('./data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### b. Membaca file JSON

In [3]:
import pandas as pd

df = pd.read_json('./data.json')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### c. Menggunakan Parameter pada Pandas Read

In [4]:
df = pd.read_csv('./data.csv', sep=',', header=0)
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### d. Membaca Custom Data

In [5]:
import pandas as pd

# Data latihan
data = {
    "Duration": {
        "0": 60,
        "1": 60,
        "2": 60,
        "3": 45
    },
    "Pulse": {
        "0": 110,
        "1": 117,
        "2": 103,
        "3": 109
    },
    "Maxpulse": {
        "0": 130,
        "1": 145,
        "2": 135,
        "3": 175
    },
    "Calories": {
        "0": 409,
        "1": 479,
        "2": 340,
        "3": 282
    }
}

# Membuat DataFrame dari dictionary
df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282

## 2.	Membuat dan Mengakses Elemen Series

### a. Membuat Series dari sebuah List Python

In [6]:
import pandas as pd
li = [1, 7, 2]
se = pd.Series(li)
print(se)

0    1
1    7
2    2
dtype: int64

### b.	Mengakses Elemen pada Series

In [7]:
li = [1, 7, 2]
se = pd.Series(li)
print(se[0])

1

### c. Memberi Label pada series

In [8]:
li = [1, 7, 2]
se = pd.Series(li, index = ['x', 'y', 'z'])
print(se['x'])

1

### c. Membuat Series dari Dictionary

In [9]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)
print(se)

day1    420
day2    380
day3    390
dtype: int64

## 3. Membuat DataFrame

### a. Membuat DataFrame

In [31]:
import pandas as pd


df1 = pd.DataFrame(data={
    "Nama": ["Ali", "Joko", "Adi"],
    "Umur": [12, 13, 15],
    "Kelas": [6, 7, 8]
})


df1.columns.values[0] = "Nama Singkat"


print("DataFrame 1:")
print(df1)


data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df2 = pd.DataFrame(data)


print("\nDataFrame 2:")
print(df2)

DataFrame 1:
  Nama Singkat  Umur  Kelas
0          Ali    12      6
1         Joko    13      7
2          Adi    15      8

DataFrame 2:
   calories  duration
0       420        50
1       380        40
2       390        45

### b. Mengakses Elemen pada DataFrame

In [34]:


df2.iloc[0:2, [0,1]]
df2.iloc[0:2, 0:2]
df2.iloc[:, 0:2]
df2.loc[0:2, :'calories']
df2.loc[0:2, ['calories', 'duration']]
df2['calories']
df2['calories'] [0]
df2[['calories']]
df2[['calories']].loc[[0,1]]

   calories
0       420
1       380

### c. Memberi nama pada index

In [13]:
	data = {
	  "calories": [420, 380, 390],
	  "duration": [50, 40, 45]
	}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45

      calories  duration
day1       420        50
day2       380        40
day3       390        45

### d. Melihat DataFrame

In [14]:
df = pd.read_csv('./data.csv')
print(df)
df
df.head()
df.tail()
df.head(10)
df.shape
df.dtypes

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### e. Membaca Informasi pada DataFrame

In [15]:
df.info()
df.describe()
df['Calories'].mean(), df['Calories'].median(),
df['Calories'].mode() [0]
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

## Tugas Praktikkum

In [16]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
df

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
5,5,5555,Dominic Calvert-Lewin,32,2788,16,18.136449,0,2.101819,82,18,3,0,F S,Everton,16,18.136449,19.698850,4.159406
6,6,755,Jamie Vardy,34,2848,15,19.942946,9,5.087882,82,28,1,0,F S,Leicester,7,13.092427,18.227907,2.412588
7,7,8865,Ollie Watkins,37,3330,14,16.280178,5,5.314029,98,45,2,1,F,Aston Villa,13,14.757840,22.014021,5.334991
8,8,314,Ilkay Gündogan,28,2033,13,9.566883,2,3.816220,54,42,1,0,M S,Manchester City,12,8.044545,19.286812,10.148375
9,9,3277,Alexandre Lacazette,30,1928,13,12.028909,2,2.209213,45,22,3,0,F M S,Arsenal,10,9.745403,14.361542,2.937941
10,10,468,Callum Wilson,26,2079,12,13.590091,5,3.046301,49,17,2,0,F S,Newcastle United,8,10.545416,14.205593,1.052545
11,11,620,Kelechi Iheanacho,25,1452,12,9.048596,2,3.534099,59,28,1,0,F S,Leicester,12,8.287427,13.961564,3.429915
12,12,986,Danny Ings,28,2115,12,8.139229,4,2.311231,56,22,1,0,F S,Southampton,10,6.616892,9.929089,2.063256
13,13,4456,Chris Wood,32,2675,12,12.896009,3,2.038118,69,23,0,0,F S,Burnley,10,11.373671,13.585282,2.149852
14,14,522,Wilfried Zaha,30,2615,11,8.804440,2,3.702821,60,30,6,0,F M S,Crystal Palace,9,7.282102,13.579472,3.634436
15,15,556,Marcus Rashford,37,2941,11,9.579710,9,4.185122,79,44,4,0,F M S,Manchester United,11,9.579710,20.441910,8.927208
16,16,838,Sadio Mané,35,2805,11,14.828548,7,7.787755,94,61,3,0,F M S,Liverpool,11,14.828548,24.998923,6.057656
17,17,2251,Gareth Bale,20,909,11,5.797858,2,1.842241,38,21,1,0,M S,Tottenham,11,5.797858,8.149641,2.594514
18,18,7153,Matheus Pereira,33,2594,11,6.948317,6,6.355539,65,58,2,1,M S,West Bromwich Albion,7,3.903641,10.857054,3.757924
19,19,318,Pierre-Emerick Aubameyang,28,2254,10,10.194089,3,2.352407,55,19,2,0,F M S,Arsenal,8,8.671751,14.778998,3.955129
20,20,531,Michail Antonio,25,1923,10,14.138839,5,3.034945,63,25,3,0,F S,West Ham,10,14.138839,18.998891,2.655064
21,21,606,Christian Benteke,30,1824,10,7.457401,1,0.697626,71,15,1,1,F S,Crystal Palace,10,7.457401,8.472840,3.153554
22,22,618,Raheem Sterling,30,2449,10,11.763264,6,5.817096,68,35,3,0,F M S,Manchester City,10,11.002095,24.088666,11.477125
23,23,3294,Edinson Cavani,26,1355,10,8.603232,3,2.317244,34,14,4,0,F S,Manchester United,10,8.603232,12.259187,2.730645
24,24,5612,Anwar El Ghazi,28,1612,10,9.037518,0,1.882866,64,26,2,0,F M S,Aston Villa,6,5.992842,7.845563,2.691346
25,25,8288,Tomas Soucek,37,3330,10,8.936490,1,2.329664,63,17,7,1,M,West Ham,10,8.936490,16.730340,8.610449
26,26,482,Roberto Firmino,36,2882,9,12.860213,7,6.116863,83,44,2,0,F M S,Liverpool,9,12.860213,25.271458,10.198550
27,27,558,Jesse Lingard,15,1344,9,5.095250,4,2.329288,39,18,3,0,F M,West Ham,8,3.572913,9.868648,5.617283
28,28,750,Riyad Mahrez,26,1894,9,6.151046,5,5.954979,56,43,0,0,F M S,Manchester City,9,6.151046,18.641168,9.019600
29,29,6681,Harvey Barnes,25,1954,9,6.697320,4,1.771688,56,26,0,0,F M S,Leicester,9,6.697320,8.893774,1.594841
30,30,6854,Diogo Jota,19,1114,9,7.057721,0,1.762521,46,12,2,0,F M S,Liverpool,9,7.057721,10.972975,4.076096
31,31,7700,Che Adams,36,2685,9,12.118734,5,5.227754,55,37,1,0,F S,Southampton,9,12.118734,14.486912,2.744624
32,32,843,James Ward-Prowse,37,3330,8,5.427161,7,3.956646,42,57,5,0,D M,Southampton,5,2.382486,10.150620,8.928799
33,33,1776,Jarrod Bowen,37,2514,8,7.817086,5,4.952178,53,28,0,0,F M S,West Ham,8,7.817086,14.000131,3.096995
34,34,3621,Neal Maupay,33,2526,8,13.773535,2,4.277408,71,32,1,1,F M S,Brighton,5,10.728933,17.157539,3.381785
35,35,5543,Gabriel Jesus,28,1977,8,9.009614,4,3.371890,52,29,2,0,F M S,Manchester City,8,9.009614,16.564744,5.563635
36,36,5656,Nicolas Pepe,28,1512,8,5.811174,1,1.012160,43,11,1,1,F M S,Arsenal,7,5.050005,9.170708,4.217726
37,37,6055,Phil Foden,27,1548,8,5.437581,5,4.749281,43,36,0,0,F M S,Manchester City,8,5.437581,13.111077,5.408362
38,38,6630,Joe Willock,21,1215,8,5.088090,0,0.733701,23,10,1,0,M S,"Arsenal,Newcastle United",8,4.326921,7.007069,2.987727
39,39,6818,James Maddison,31,2123,8,3.827570,5,5.386724,75,50,4,0,M S,Leicester,8,3.827570,11.743431,6.073130
40,40,8718,Stuart Dallas,38,3412,8,4.457074,2,2.084683,48,26,7,0,D M,Leeds,8,4.457074,18.534344,13.809802
41,41,8720,Jack Harrison,36,2871,8,6.254043,8,7.523059,46,59,2,0,M S,Leeds,8,6.254043,19.397490,8.035575
42,42,695,Bertrand Traoré,36,2362,7,6.304105,6,4.570988,64,35,1,0,F M S,Aston Villa,7,6.304105,9.835355,1.332214
43,43,1389,Jorginho,28,2022,7,6.972691,1,1.954869,14,24,2,0,M S,Chelsea,0,0.122245,11.383730,10.878975
44,44,2381,Rodrigo,26,1285,7,5.755642,2,3.200529,46,31,3,0,F M S,Leeds,7,5.755642,10.815974,4.348653
45,45,6026,Richarlison,33,2803,7,10.427272,3,3.394761,78,25,3,1,F M S,Everton,6,9.666103,15.678683,5.174453
46,46,6441,Ferrán Torres,23,1291,7,5.728708,2,2.202426,36,18,1,0,F M S,Manchester City,7,5.728708,9.768891,2.724257
47,47,7490,Mason Greenwood,31,1825,7,6.975748,2,2.427900,67,14,2,0,F M S,Manchester United,7,6.975748,14.031833,5.954059
48,48,7711,David McGoldrick,34,2319,7,7.383084,1,1.050454,65,16,7,0,F M S,Sheffield United,7,7.383084,9.682009,3.187532
49,49,65,Timo Werner,35,2605,6,13.432796,8,6.667277,80,36,2,0,F M S,Chelsea,6,13.432796,20.533463,5.242122
50,50,501,Danny Welbeck,24,1551,6,7.380382,1,3.231367,35,22,0,0,F M S,Brighton,6,6.619249,10.265667,1.476513
51,51,675,Jack Grealish,26,2187,6,5.192684,10,9.334137,50,81,5,0,F M S,Aston Villa,6,5.192684,17.487469,6.972044
52,52,702,Tammy Abraham,22,1027,6,6.189151,1,0.721487,32,9,0,0,F S,Chelsea,6,6.189151,7.901170,2.122328
53,53,714,Gylfi Sigurdsson,35,2189,6,5.620114,5,4.763621,46,43,2,0,F M S,Everton,3,3.336608,8.377621,3.660514
54,54,2249,James Rodríguez,23,1802,6,3.363538,4,5.439712,37,40,4,0,F M S,Everton,6,3.363538,12.033005,7.104181
55,55,5956,Youri Tielemans,38,3359,6,4.168204,4,3.312251,48,49,6,0,M S,Leicester,4,2.645866,18.975342,14.945469
56,56,7768,Mason Mount,36,2891,6,6.884880,5,9.847691,82,87,2,0,F M S,Chelsea,5,6.123712,21.696074,12.443149
57,57,8026,Raphinha,30,2369,6,6.219143,9,9.524861,67,65,3,0,M S,Leeds,6,6.219143,16.792778,6.679692
58,58,447,Kevin De Bruyne,24,1918,5,9.908440,11,10.003763,79,72,1,0,M S,Manchester City,3,7.624933,21.079132,10.636448
59,59,935,Kurt Zouma,24,2024,5,3.136853,0,0.081467,27,4,3,0,D S,Chelsea,5,3.136853,6.216146,6.133133
60,60,4476,Callum Robinson,28,1580,5,3.203063,0,1.049963,31,16,0,0,F M S,West Bromwich Albion,5,3.203063,5.216541,1.596336
61,61,6048,Lewis Dunk,32,2844,5,2.699258,0,0.830638,31,10,5,2,D,Brighton,5,2.699258,8.265678,7.870709
62,62,6382,Pedro Neto,31,2570,5,5.494996,6,5.738268,62,61,4,0,F M S,Wolverhampton Wanderers,5,5.494996,11.516662,4.206935
63,63,6827,Bobby Reid,33,2394,5,4.269852,2,1.309701,34,14,7,0,D F M S,Fulham,5,4.269852,8.202645,3.131384
64,64,6853,Rúben Neves,35,2591,5,4.715056,1,2.002833,65,32,7,0,M S,Wolverhampton Wanderers,2,2.431550,6.769232,4.476360
65,65,7322,Bukayo Saka,31,2561,5,7.169174,3,4.511791,61,38,1,0,D F M S,Arsenal,5,7.169174,18.292466,9.180440
66,66,7698,Leandro Trossard,34,2601,5,5.412756,5,5.398416,58,51,2,0,F M S,Brighton,5,5.412756,15.998935,7.631562
67,67,87,Joelinton,31,2006,4,5.631002,2,2.366481,43,17,3,0,F M S,Newcastle United,3,4.869833,9.268311,3.284958
68,68,502,Olivier Giroud,17,750,4,5.070416,0,1.175799,29,6,1,0,F S,Chelsea,4,5.070416,5.245491,1.711337
69,69,553,Anthony Martial,22,1494,4,7.405651,3,2.619803,42,17,0,1,F M S,Manchester United,4,7.405651,11.814813,3.319505
70,70,586,John Stones,21,1843,4,2.393954,0,0.046840,14,2,0,1,D,Manchester City,4,2.393954,9.842464,9.742795
71,71,2662,Christian Pulisic,27,1739,4,6.775412,2,2.761232,43,25,2,0,F M S,Chelsea,4,6.775412,14.593858,7.101120
72,72,4105,Raúl Jiménez,10,824,4,2.360910,0,0.632963,26,6,0,0,F,Wolverhampton Wanderers,4,2.360910,3.684076,1.233211
73,73,4381,Mateusz Klich,35,2404,4,2.999959,5,3.650850,36,44,6,0,M S,Leeds,2,1.477621,14.608117,10.386438
74,74,5220,Kai Havertz,27,1523,4,6.352184,3,1.553382,33,18,2,0,F M S,Chelsea,4,6.352184,10.382944,4.811911
75,75,5556,Ademola Lookman,34,2765,4,6.251116,4,5.258407,69,61,5,0,F M S,Fulham,4,5.489947,15.355220,7.334159
76,76,5560,Scott McTominay,32,2121,4,1.847744,1,2.114613,26,17,3,0,M S,Manchester United,4,1.847744,10.912294,7.904810
77,77,6893,Stuart Armstrong,32,2701,4,2.562590,5,2.518058,51,33,3,0,M S,Southampton,4,2.562590,9.479516,6.250184
78,78,7420,Miguel Almirón,34,2458,4,3.509382,1,3.135925,33,31,3,0,F M S,Newcastle United,4,3.509382,9.295024,3.899067
79,79,8706,Eberechi Eze,34,2570,4,2.494572,6,3.741962,37,42,3,0,M S,Crystal Palace,4,2.494572,7.996477,3.959955
80,80,8778,Fabio Silva,31,1251,4,5.958539,2,1.035431,45,10,2,0,F S,Wolverhampton Wanderers,3,5.197370,4.897674,1.070238
81,81,101,Allan Saint-Maximin,25,1578,3,2.825913,4,4.013324,30,29,0,0,F M S,Newcastle United,3,2.825913,10.594720,4.224003
82,82,111,Jannik Vestergaard,29,2481,3,2.026947,0,0.740825,22,7,3,1,D S,Southampton,3,2.026947,5.853649,5.778864
83,83,239,Pascal Groß,33,2379,3,5.010526,8,5.368290,32,69,3,0,D M S,Brighton,0,1.965887,10.404419,6.732295
84,84,503,Theo Walcott,22,1660,3,2.280677,3,1.263103,29,17,0,0,F M S,"Everton,Southampton",3,2.280677,5.551979,2.233550
85,85,528,Angelo Ogbonna,27,2403,3,1.696074,0,0.428471,13,4,5,0,D,West Ham,3,1.696074,3.929544,3.707049
86,86,592,Ross Barkley,26,1574,3,3.699934,1,4.319003,39,40,0,0,M S,"Aston Villa,Chelsea",3,3.699934,9.896903,3.717251
87,87,669,Ashley Westwood,37,3322,3,1.005990,3,6.352089,19,49,7,0,M,Burnley,3,1.005990,10.010638,6.287275
88,88,773,Aleksandar Mitrovic,27,1369,3,5.677363,3,2.924711,59,23,3,0,F S,Fulham,2,4.155025,7.808299,1.849482
89,89,782,Ben Chilwell,27,2296,3,2.984890,5,2.455678,27,30,3,0,D M,Chelsea,3,2.984890,11.330961,8.155132
90,90,804,Craig Dawson,21,1835,3,2.692452,0,0.054468,15,2,3,1,D,West Ham,3,2.692452,2.926758,2.926758
91,91,964,Kyle Bartley,30,2581,3,2.601400,1,0.759965,14,7,4,0,D S,West Bromwich Albion,3,2.601400,2.484649,1.499340
92,92,1017,Matej Vydra,27,1322,3,5.373273,2,2.118341,35,14,0,0,F S,Burnley,3,5.373273,6.425857,1.047204
93,93,1653,Michael Keane,34,2896,3,1.504692,1,1.085253,16,7,4,0,D S,Everton,3,1.504692,6.840393,6.564230
94,94,1740,Paul Pogba,26,1893,3,2.988203,3,2.066863,31,24,3,0,M S,Manchester United,3,2.988203,11.691473,7.444205
95,95,2335,Pablo Fornals,32,2513,3,5.854255,3,2.054639,46,28,3,0,F M S,West Ham,3,5.854255,14.868231,8.320600
96,96,3293,Lucas Moura,30,1392,3,1.946633,4,2.064035,18,16,1,0,F M S,Tottenham,3,1.946633,7.514038,5.200065
97,97,3428,Hélder Costa,22,1152,3,2.598155,3,0.628334,16,7,0,0,M S,Leeds,3,2.598155,4.516011,2.207326
98,98,3491,Romain Saiss,26,2319,3,3.099968,0,0.648440,27,4,2,0,D,Wolverhampton Wanderers,3,3.099968,4.538973,3.720983
99,99,3683,Ivan Cavaleiro,36,2477,3,5.548667,0,2.680474,47,42,2,0,D F M S,Fulham,2,4.026329,8.240886,2.856730
100,100,4422,Ashley Barnes,21,1341,3,3.874066,0,0.800548,38,19,4,0,F M S,Burnley,2,3.112897,4.190315,1.198629
101,101,5587,Josh Maja,15,809,3,4.918053,0,0.742830,21,7,0,0,F S,Fulham,2,4.156885,4.449021,0.645544
102,102,5595,Daniel James,14,830,3,1.943297,0,0.740844,16,7,3,0,M S,Manchester United,3,1.943297,4.284208,1.735916
103,103,5962,Tanguy NDombele Alvaro,33,2141,3,1.530482,2,2.126334,18,14,3,0,M S,Tottenham,3,1.530482,10.934965,8.005785
104,104,6144,Sébastien Haller,16,933,3,2.554668,0,1.134868,25,10,0,0,F S,West Ham,3,2.554668,3.660330,0.852949
105,105,7712,Billy Sharp,16,723,3,2.983077,0,0.583278,9,4,1,0,F S,Sheffield United,1,1.460739,2.650699,0.664895
106,106,7723,John McGinn,37,3330,3,2.166595,5,3.501758,45,42,12,0,M,Aston Villa,3,2.166595,14.868267,9.945619
107,107,8239,Takumi Minamino,18,941,3,2.557263,0,0.762515,18,4,1,0,F M S,"Liverpool,Southampton",3,2.557263,5.954796,2.767797
108,108,8291,Daniel Podence,24,1718,3,2.744378,2,1.839433,32,21,3,0,F M S,Wolverhampton Wanderers,3,2.744378,6.725103,2.910881
109,109,9290,Mbaye Diagne,16,1205,3,6.247825,2,0.986101,25,10,2,0,F S,West Bromwich Albion,3,6.247825,8.729951,1.773010
110,110,343,Pierre-Emile Højbjerg,38,3420,2,1.137927,4,1.755895,14,16,9,0,M,Tottenham,2,1.137927,16.205809,14.680379
111,111,619,Sergio Agüero,11,533,2,3.002216,1,1.315660,15,7,0,0,F M S,Manchester City,1,1.479878,3.363660,1.145450
112,112,725,Ola Aina,31,2683,2,0.847976,1,1.552728,14,15,3,0,D M,Fulham,2,0.847976,6.773145,6.120467
113,113,757,Jeffrey Schlupp,27,1424,2,2.015116,3,2.572583,18,18,3,0,M S,Crystal Palace,2,2.015116,5.158029,3.466957
114,114,766,Jamaal Lascelles,19,1633,2,0.765355,0,0.066883,16,2,4,0,D,Newcastle United,2,0.765355,2.606450,2.349908
115,115,770,Ayoze Pérez,25,1326,2,4.036575,1,1.248606,31,23,2,0,F M S,Leicester,2,4.036575,9.872759,6.759956
116,116,771,Georginio Wijnaldum,38,2961,2,2.817427,0,1.662922,31,21,1,0,M S,Liverpool,2,2.817427,13.922182,10.476277
117,117,790,Nathan Redmond,28,1628,2,3.793103,3,2.987434,44,22,1,0,F M S,Southampton,2,3.793103,8.591277,3.182593
118,118,807,Jonny Evans,28,2483,2,1.855713,2,0.538631,8,10,7,0,D,Leicester,2,1.855713,8.730610,7.942967
119,119,900,Adama Traoré,36,2604,2,1.995262,2,5.228081,41,54,4,0,D F M S,Wolverhampton Wanderers,2,1.995262,9.373142,3.006398
120,120,1024,Tyrone Mings,36,3194,2,2.061613,2,0.376271,19,7,4,1,D,Aston Villa,2,2.061613,6.932439,6.708538
121,121,1621,Marcos Alonso,13,962,2,1.824078,0,1.721699,22,15,2,0,D S,Chelsea,2,1.824078,4.643396,2.536424
122,122,1654,Ben Mee,30,2695,2,1.619416,0,0.805204,22,7,3,0,D,Burnley,2,1.619416,2.118282,2.015906
123,123,1663,Johann Berg Gudmundsson,21,1279,2,1.516047,0,0.959504,18,10,2,0,M S,Burnley,2,1.516047,3.596362,1.325504
124,124,1678,Michy Batshuayi,18,706,2,1.363145,1,1.654721,12,9,0,0,F S,Crystal Palace,2,1.363145,3.708007,1.475732
125,125,1687,Harry Maguire,34,3049,2,1.484337,1,0.290943,36,7,11,0,D,Manchester United,2,1.484337,13.127004,13.018347
126,126,1726,Abdoulaye Doucouré,28,2409,2,2.369523,3,2.381616,18,20,6,0,M,Everton,2,2.369523,10.355722,6.733990
127,127,1737,Matt Phillips,33,1823,2,2.923517,1,3.245671,22,25,1,0,M S,West Bromwich Albion,2,2.923517,7.040552,2.613231
128,128,1738,Hal Robson-Kanu,19,522,2,1.496081,0,0.243450,13,5,2,0,F S,West Bromwich Albion,2,1.496081,2.264205,0.634409
129,129,1746,Jeff Hendrick,22,1436,2,1.107994,1,1.433230,10,6,1,1,M S,Newcastle United,2,1.107994,3.605642,1.386696
130,130,1791,Trent Alexander-Arnold,36,3040,2,2.593060,7,8.576368,55,77,2,0,D S,Liverpool,2,2.593060,23.107881,17.648908
131,131,2379,João Cancelo,28,2309,2,1.865636,3,5.177640,35,45,5,1,D M S,Manchester City,2,1.865636,18.105726,14.480545
132,132,2496,Rodri,33,2719,2,2.538604,2,2.335383,31,33,6,0,M S,Manchester City,1,1.777435,20.214505,18.323006
133,133,3203,Issa Diop,17,1378,2,0.953531,0,0.017780,3,1,3,0,D S,West Ham,2,0.953531,2.147921,1.831723
134,134,3288,Thiago Silva,23,1938,2,1.320545,0,0.291494,13,5,3,1,D,Chelsea,2,1.320545,7.842858,7.636919
135,135,3389,Benjamin Mendy,13,955,2,0.334141,1,0.301440,6,5,2,0,D M S,Manchester City,2,0.334141,2.769137,2.348603
136,136,3600,Serge Aurier,19,1619,2,1.475272,3,3.719394,15,17,0,0,D M,Tottenham,2,1.475272,8.711732,5.293096
137,137,3635,Bernardo Silva,26,2080,2,3.598813,6,4.823390,28,27,5,0,F M S,Manchester City,2,3.598813,17.112390,10.653521
138,138,4490,Semi Ajayi,33,2773,2,1.733796,0,0.510466,13,7,3,1,D S,West Bromwich Albion,2,1.733796,4.629277,3.112332
139,139,5584,Aaron Wan-Bissaka,34,3060,2,0.932454,4,2.547663,7,31,3,0,D,Manchester United,2,0.932454,12.242123,9.676275
140,140,5613,Gabriel,22,1904,2,1.550638,0,0.056096,15,2,2,1,D S,Arsenal,2,1.550638,5.588361,5.573927
141,141,6027,Jairo Riedewald,33,1803,2,0.563081,0,0.897361,8,11,4,0,M S,Crystal Palace,2,0.563081,3.511385,2.333951
142,142,6049,Solly March,21,1684,2,1.783602,1,1.678820,22,27,0,0,D M S,Brighton,2,1.783602,8.322110,5.680549
143,143,6063,Jacob Murphy,26,1611,2,1.490953,3,3.433489,30,19,3,0,D M S,Newcastle United,2,1.490953,8.043614,4.102316
144,144,6157,Timothy Castagne,27,2349,2,1.600267,3,2.306963,8,21,1,0,D M,Leicester,2,1.600267,8.445917,6.606227
145,145,6456,Callum Hudson-Odoi,23,1048,2,1.369689,3,3.104142,23,31,0,0,D F M S,Chelsea,2,1.369689,7.824358,5.499199
146,146,6482,Eddie Nketiah,17,405,2,2.022099,1,0.742355,12,8,0,0,F S,Arsenal,2,2.022099,2.077280,0.220550
147,147,6521,Yerry Mina,24,1941,2,1.749434,0,0.019599,17,1,2,0,D S,Everton,2,1.749434,4.313141,4.212719
148,148,6756,Dwight McNeil,35,3002,2,1.006853,5,5.418881,25,46,1,0,M S,Burnley,2,1.006853,6.874772,3.606812
149,149,7230,Emile Smith-Rowe,19,1382,2,1.592160,4,3.449014,13,23,0,0,M S,Arsenal,2,1.592160,9.202460,5.454993
150,150,7722,Trézéguet,21,1175,2,3.979035,1,2.147568,35,13,0,0,F M S,Aston Villa,2,3.979035,7.027209,1.903933
151,151,7726,Ezri Konsa Ngoyo,36,3192,2,3.291559,0,0.093177,22,2,3,0,D S,Aston Villa,2,3.291559,3.429550,3.381944
152,152,7752,Gabriel Martinelli,13,577,2,3.252450,1,1.745651,20,9,0,0,F M S,Arsenal,2,3.252450,6.159720,1.756597
153,153,7753,James Justin,23,2070,2,1.517483,1,2.059136,9,19,4,0,D,Leicester,2,1.517483,7.665664,5.505036
154,154,7991,Aaron Connolly,16,755,2,4.412464,1,0.149897,22,5,0,0,F M S,Brighton,2,4.412464,4.720931,0.191225
155,155,8722,Ezgjan Alioski,36,2475,2,1.746611,3,3.332753,25,28,7,0,D M S,Leeds,2,1.746611,13.478340,9.686266
156,156,8992,Hakim Ziyech,23,1182,2,1.987314,3,4.478449,35,34,3,0,F M S,Chelsea,2,1.987314,7.660672,3.691924
157,157,9040,Conor Gallagher,30,2529,2,1.542326,2,1.418288,29,21,11,0,M S,West Bromwich Albion,2,1.542326,5.059540,3.124785
158,158,9205,Jayden Bogle,16,1109,2,1.915020,0,0.208554,17,4,2,0,D M S,Sheffield United,2,1.915020,2.668701,1.365645
159,159,76,Fabian Schär,18,1252,1,1.460577,0,0.000000,12,0,4,1,D S,Newcastle United,0,0.699408,0.955123,0.873561
160,160,204,Granit Xhaka,30,2447,1,0.711673,2,1.334161,18,14,7,1,D M S,Arsenal,1,0.711673,13.537367,12.521644
161,161,229,Thiago Alcántara,24,1865,1,1.211306,0,2.554922,22,30,4,0,M S,Liverpool,1,1.211306,11.152549,9.468282
162,162,332,Joel Matip,10,701,1,0.784475,2,1.180275,5,3,2,0,D S,Liverpool,1,0.784475,4.383128,4.383128
163,163,486,Adam Lallana,29,1528,1,1.614306,1,2.628758,22,25,0,0,F M S,Brighton,1,1.614306,9.719970,5.874305
164,164,492,Héctor Bellerín,25,2098,1,0.860230,2,2.171512,15,21,8,0,D S,Arsenal,1,0.860230,8.059892,6.266996
165,165,496,Mohamed Elneny,23,1540,1,0.475616,0,0.256942,9,4,3,0,M S,Arsenal,1,0.475616,5.195761,4.651168
166,166,500,Alex Iwobi,29,1505,1,0.843632,2,2.155349,15,16,0,0,D F M S,Everton,1,0.843632,7.218916,4.475585
167,167,512,Scott Dann,15,1350,1,0.548289,0,0.017613,4,1,1,0,D,Crystal Palace,1,0.548289,1.185210,1.167598
168,168,532,Cheikhou Kouyaté,36,3126,1,0.823928,0,0.830787,7,8,4,0,D M S,Crystal Palace,1,0.823928,4.744332,4.530509
169,169,535,Manuel Lanzini,17,548,1,0.971057,1,1.001792,12,11,1,0,M S,West Ham,1,0.971057,3.232661,1.579505
170,170,537,Andy Carroll,18,369,1,0.603317,0,0.063020,13,2,1,0,F S,Newcastle United,1,0.603317,0.989015,0.542128
171,171,579,Nathan Aké,10,802,1,0.505318,0,0.017229,3,1,4,0,D S,Manchester City,1,0.505318,4.211259,4.194029
172,172,605,Jordan Henderson,21,1710,1,1.135798,1,1.483709,14,14,0,0,D M S,Liverpool,1,1.135798,11.494361,10.461348
173,173,638,Kyle Walker,23,1854,1,0.204405,1,0.499786,10,8,1,0,D S,Manchester City,1,0.204405,9.922639,9.524867
174,174,639,Toby Alderweireld,25,2243,1,0.613819,0,0.968030,10,8,2,0,D,Tottenham,1,0.613819,5.900501,5.857219
175,175,644,Erik Lamela,23,683,1,1.289413,0,0.805832,21,8,4,1,F M S,Tottenham,1,1.289413,4.192472,2.828798

In [17]:
import pandas as pd
df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("5 Data Pertama:\n", df.head())

5 Data Pertama:
    Unnamed: 0    id      player_name  games  time  goals         xG  assists  \
0           0   647       Harry Kane     35  3097     23  22.174859       14
1           1  1250    Mohamed Salah     37  3085     22  20.250847        5
2           2  1228  Bruno Fernandes     37  3117     18  16.019454       12
3           3   453    Son Heung-Min     37  3139     17  11.023287       10
4           4   822  Patrick Bamford     38  3085     17  18.401863        7

          xA  shots  key_passes  yellow_cards  red_cards position  \
0   7.577094    138          49             1          0        F
1   6.528526    126          55             0          0    F M S
2  11.474996    121          95             6          0      M S
3   9.512992     68          75             0          0    F M S
4   3.782247    107          30             3          0      F S

          team_title  npg       npxG    xGChain  xGBuildup
0          Tottenham   19  19.130183  24.995648   4.451257
1          Liverpool   16  15.683834  28.968234   9.800236
2  Manchester United    9   8.407840  26.911412  11.932285
3          Tottenham   16  10.262118  20.671916   6.608751
4              Leeds   15  16.879525  23.394953   4.131796

In [18]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\nJumlah Baris dan Kolom:", df.shape)

Jumlah Baris dan Kolom: (522, 19)

In [19]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\nTipe Data Kolom:\n", df.dtypes)

Tipe Data Kolom:
 Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

In [20]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\nJumlah Goal Tiap Pemain:\n", df[['player_name', 'goals']])

Jumlah Goal Tiap Pemain:
                    player_name  goals
0                   Harry Kane     23
1                Mohamed Salah     22
2              Bruno Fernandes     18
3                Son Heung-Min     17
4              Patrick Bamford     17
5        Dominic Calvert-Lewin     16
6                  Jamie Vardy     15
7                Ollie Watkins     14
8               Ilkay Gündogan     13
9          Alexandre Lacazette     13
10               Callum Wilson     12
11           Kelechi Iheanacho     12
12                  Danny Ings     12
13                  Chris Wood     12
14               Wilfried Zaha     11
15             Marcus Rashford     11
16                  Sadio Mané     11
17                 Gareth Bale     11
18             Matheus Pereira     11
19   Pierre-Emerick Aubameyang     10
20             Michail Antonio     10
21           Christian Benteke     10
22             Raheem Sterling     10
23              Edinson Cavani     10
24              Anwar El Ghazi     10
25                Tomas Soucek     10
26             Roberto Firmino      9
27               Jesse Lingard      9
28                Riyad Mahrez      9
29               Harvey Barnes      9
30                  Diogo Jota      9
31                   Che Adams      9
32           James Ward-Prowse      8
33                Jarrod Bowen      8
34                 Neal Maupay      8
35               Gabriel Jesus      8
36                Nicolas Pepe      8
37                  Phil Foden      8
38                 Joe Willock      8
39              James Maddison      8
40               Stuart Dallas      8
41               Jack Harrison      8
42             Bertrand Traoré      7
43                    Jorginho      7
44                     Rodrigo      7
45                 Richarlison      7
46               Ferrán Torres      7
47             Mason Greenwood      7
48            David McGoldrick      7
49                 Timo Werner      6
50               Danny Welbeck      6
51               Jack Grealish      6
52               Tammy Abraham      6
53            Gylfi Sigurdsson      6
54             James Rodríguez      6
55             Youri Tielemans      6
56                 Mason Mount      6
57                    Raphinha      6
58             Kevin De Bruyne      5
59                  Kurt Zouma      5
60             Callum Robinson      5
61                  Lewis Dunk      5
62                  Pedro Neto      5
63                  Bobby Reid      5
64                 Rúben Neves      5
65                 Bukayo Saka      5
66            Leandro Trossard      5
67                   Joelinton      4
68              Olivier Giroud      4
69             Anthony Martial      4
70                 John Stones      4
71           Christian Pulisic      4
72                Raúl Jiménez      4
73               Mateusz Klich      4
74                 Kai Havertz      4
75             Ademola Lookman      4
76             Scott McTominay      4
77            Stuart Armstrong      4
78              Miguel Almirón      4
79                Eberechi Eze      4
80                 Fabio Silva      4
81         Allan Saint-Maximin      3
82          Jannik Vestergaard      3
83                 Pascal Groß      3
84                Theo Walcott      3
85              Angelo Ogbonna      3
86                Ross Barkley      3
87             Ashley Westwood      3
88         Aleksandar Mitrovic      3
89                Ben Chilwell      3
90                Craig Dawson      3
91                Kyle Bartley      3
92                 Matej Vydra      3
93               Michael Keane      3
94                  Paul Pogba      3
95               Pablo Fornals      3
96                 Lucas Moura      3
97                Hélder Costa      3
98                Romain Saiss      3
99              Ivan Cavaleiro      3
100              Ashley Barnes      3
101                  Josh Maja      3
102               Daniel James      3
103     Tanguy NDombele Alvaro      3
104           Sébastien Haller      3
105                Billy Sharp      3
106                John McGinn      3
107            Takumi Minamino      3
108             Daniel Podence      3
109               Mbaye Diagne      3
110      Pierre-Emile Højbjerg      2
111              Sergio Agüero      2
112                   Ola Aina      2
113            Jeffrey Schlupp      2
114           Jamaal Lascelles      2
115                Ayoze Pérez      2
116        Georginio Wijnaldum      2
117             Nathan Redmond      2
118                Jonny Evans      2
119               Adama Traoré      2
120               Tyrone Mings      2
121              Marcos Alonso      2
122                    Ben Mee      2
123    Johann Berg Gudmundsson      2
124            Michy Batshuayi      2
125              Harry Maguire      2
126         Abdoulaye Doucouré      2
127              Matt Phillips      2
128            Hal Robson-Kanu      2
129              Jeff Hendrick      2
130     Trent Alexander-Arnold      2
131               João Cancelo      2
132                      Rodri      2
133                  Issa Diop      2
134               Thiago Silva      2
135             Benjamin Mendy      2
136               Serge Aurier      2
137             Bernardo Silva      2
138                 Semi Ajayi      2
139          Aaron Wan-Bissaka      2
140                    Gabriel      2
141            Jairo Riedewald      2
142                Solly March      2
143               Jacob Murphy      2
144           Timothy Castagne      2
145         Callum Hudson-Odoi      2
146              Eddie Nketiah      2
147                 Yerry Mina      2
148              Dwight McNeil      2
149           Emile Smith-Rowe      2
150                  Trézéguet      2
151           Ezri Konsa Ngoyo      2
152         Gabriel Martinelli      2
153               James Justin      2
154             Aaron Connolly      2
155             Ezgjan Alioski      2
156               Hakim Ziyech      2
157            Conor Gallagher      2
158               Jayden Bogle      2
159               Fabian Schär      1
160               Granit Xhaka      1
161           Thiago Alcántara      1
162                 Joel Matip      1
163               Adam Lallana      1
164            Héctor Bellerín      1
165             Mohamed Elneny      1
166                 Alex Iwobi      1
167                 Scott Dann      1
168           Cheikhou Kouyaté      1
169             Manuel Lanzini      1
170               Andy Carroll      1
171                 Nathan Aké      1
172           Jordan Henderson      1
173                Kyle Walker      1
174          Toby Alderweireld      1
175                Erik Lamela      1
176                Jordan Ayew      1
177          César Azpilicueta      1
178         Ruben Loftus-Cheek      1
179                Gary Cahill      1
180                    Willian      1
181               Dwight Gayle      1
182            Marc Albrighton      1
183             Daniel Amartey      1
184              Jonjo Shelvey      1
185            Andros Townsend      1
186               Robbie Brady      1
187            Virgil van Dijk      1
188                Oriol Romeu      1
189              Jay Rodriguez      1
190               Paul Dummett      1
191               Ciaran Clark      1
192    Alex Oxlade-Chamberlain      1
193              Mason Holgate      1
194                  Luke Shaw      1
195              Tyler Roberts      1
196               Keinan Davis      1
197               Dennis Praet      1
198                    Alisson      1
199               Mario Lemina      1
200                Emil Krafth      1
201             Matthew Lowton      1
202            James Tarkowski      1
203                 David Luiz      1
204           Andrew Robertson      1
205            Oliver McBurnie      1
206            Antonio Rüdiger      1
207             Diego Llorente      1
208               Willian José      1
209            Martin Odegaard      1
210              João Moutinho      1
211              Said Benrahma      1
212            Darnell Furlong      1
213               Oliver Burke      1
214             Caglar Söyüncü      1
215              Wilfred Ndidi      1
216           Luka Milivojevic      1
217                Declan Rice      1
218              Yves Bissouma      1
219           Giovani Lo Celso      1
220       Jean-Philippe Mateta      1
221               Jan Bednarek      1
222            Victor Lindelöf      1
223           Joachim Andersen      1
224                Ben Johnson      1
225             Grady Diangana      1
226               Curtis Jones      1
227            Rayan Ait Nouri      1
228                       Fred      1
229                  Joe Bryan      1
230                Tom Cairney      1
231                 Willy Boly      1
232                Conor Coady      1
233         Morgan Gibbs-White      1
234              Kortney Hause      1
235            Ryan Fredericks      1
236            Fabián Balbuena      1
237                    Bernard      1
238         Leander Dendoncker      1
239                   Dan Burn      1
240               Karlan Grant      1
241            Carlos Vinicius      1
242               Adam Webster      1
243             Moussa Djenepo      1
244                 Ben Osborn      1
245            Conor Hourihane      1
246              Steven Alzate      1
247                Reece James      1
248             Kieran Tierney      1
249            Tyrick Mitchell      1
250              Tariq Lamptey      1
251         Nathaniel Phillips      1
252               Sander Berge      1
253            Steven Bergwijn      1
254        Alexis Mac Allister      1
255               Nathan Tella      1
256                Jimmy Dunne      1
257                Luke Thomas      1
258             Pascal Struijk      1
259            Kalvin Phillips      1
260               Joël Veltman      1
261                Liam Cooper      1
262          Donny van de Beek      1
263                 Rúben Dias      1
264                 Kean Bryan      1
265             Fabio Carvalho      1
266            Daniel Jebbison      1
267                 Bernd Leno      0
268        Andreas Christensen      0
269             Sead Kolasinac      0
270               Matt Ritchie      0
271                Joshua King      0
272               Divock Origi      0
273              Mamadou Sakho      0
274               James Milner      0
275             Calum Chambers      0
276                  Joel Ward      0
277               Martin Kelly      0
278                     Adrián      0
279              James Tomkins      0
280                 Mark Noble      0
281            Aaron Cresswell      0
282            Darren Randolph      0
283               Kieran Gibbs      0
284               David de Gea      0
285        Timothy Fosu-Mensah      0
286                  Juan Mata      0
287               Odion Ighalo      0
288             Seamus Coleman      0
289              Phil Jagielka      0
290             James McCarthy      0
291            Nathaniel Clyne      0
292                Fernandinho      0
293            Willy Caballero      0
294             James McArthur      0
295              Alex McCarthy      0
296                Hugo Lloris      0
297                  Eric Dier      0
298                  Dele Alli      0
299                 Ben Davies      0
300                Josh Onomah      0
301         Branislav Ivanovic      0
302              Nemanja Matic      0
303              Fikayo Tomori      0
304           Lukasz Fabianski      0
305         Federico Fernández      0
306                Neil Taylor      0
307                  Jack Cork      0
308             DeAndre Yedlin      0
309        Patrick van Aanholt      0
310            Jordan Pickford      0
311          Kasper Schmeichel      0
312                 Wes Morgan      0
313            Christian Fuchs      0
314          N&#039;Golo Kanté      0
315               Demarai Gray      0
316             Moussa Sissoko      0
317                Karl Darlow      0
318                 John Ruddy      0
319             Fraser Forster      0
320              Ryan Bertrand      0
321                 Shane Long      0
322              Cédric Soares      0
323             Charlie Austin      0
324               Jack Butland      0
325              Phil Bardsley      0
326               Fabian Delph      0
327               Matt Targett      0
328         Kyle Walker-Peters      0
329               Erik Pieters      0
330            Xherdan Shaqiri      0
331              Harrison Reed      0
332              Axel Tuanzebe      0
333                Harry Winks      0
334              Sam Johnstone      0
335               Joseph Gomez      0
336                  Sam Field      0
337                 Tom Davies      0
338               Jonjoe Kenny      0
339            Felipe Anderson      0
340                    Emerson      0
341                 Moise Kean      0
342                      Allan      0
343              Islam Slimani      0
344                Ryan Fraser      0
345           Ahmed Elmohamady      0
346             Jake Livermore      0
347           Robert Snodgrass      0
348           Shkodran Mustafi      0
349           Javier Manquillo      0
350              Jack Stephens      0
351                Eric Bailly      0
352                 Kevin Long      0
353                Lys Mousset      0
354                Rob Holding      0
355     Ainsley Maitland-Niles      0
356             Arthur Masuaku      0
357             Nampalys Mendy      0
358                Lucas Digne      0
359                Alex Telles      0
360            Pablo Hernández      0
361             Vicente Guaita      0
362              Mateo Kovacic      0
363               Kiko Casilla      0
364                      Jonny      0
365            Alphonse Areola      0
366              Thomas Partey      0
367                André Gomes      0
368                   Mat Ryan      0
369              Dani Ceballos      0
370            Aymeric Laporte      0
371        Oleksandr Zinchenko      0
372             Kamil Grosicki      0
373            Ricardo Pereira      0
374         Maxime Le Marchand      0
375                    Fabinho      0
376              Morgan Sanson      0
377               Ahmed Hegazy      0
378          Emiliano Martinez      0
379       Jean-Philippe Gbamin      0
380           Aboubakar Kamara      0
381            Patrick Cutrone      0
382                       Kepa      0
383                   Bernardo      0
384                 Naby Keita      0
385             Michael Hector      0
386                  Nick Pope      0
387              Rekeem Harper      0
388             Rhian Brewster      0
389           Tosin Adarabioyo      0
390             Aaron Ramsdale      0
391            Fernando Marçal      0
392                 Kenny Tete      0
393             Charlie Taylor      0
394               Davy Pröpper      0
395              Dale Stephens      0
396                    Ederson      0
397               Isaac Hayden      0
398            Terence Kongolo      0
399               Douglas Luiz      0
400               Cengiz Ünder      0
401              Nélson Semedo      0
402             José Izquierdo      0
403           Davinson Sánchez      0
404                 Robin Koch      0
405          Andriy Yarmolenko      0
406             Jayson Molumby      0
407               Ethan Ampadu      0
408                  Joe Rodon      0
409            Hamza Choudhury      0
410               Franck Zambo      0
411                 Cenk Tosun      0
412               Reiss Nelson      0
413            Michael Obafemi      0
414            Martin Dubravka      0
415            Ibrahima Diallo      0
416                Lee Peltier      0
417            Neeskens Kebano      0
418        Alireza Jahanbakhsh      0
419               David Button      0
420               Rui Patrício      0
421               Matt Doherty      0
422              Rúben Vinagre      0
423       Rúnar Alex Rúnarsson      0
424              Edouard Mendy      0
425            Mohammed Salisu      0
426               Okay Yokuslu      0
427                Robin Olsen      0
428                 Denis Odoi      0
429             Sean Longstaff      0
430                   Tim Ream      0
431            Sergio Reguilón      0
432                 Yan Valery      0
433                  Ben White      0
434               Kayne Ramsay      0
435                 Max Kilman      0
436                 Ozan Kabak      0
437                Josh Benson      0
438                Will Norris      0
439              Wesley Fofana      0
440                Ben Godfrey      0
441                Jamal Lewis      0
442             Dean Henderson      0
443                  John Egan      0
444               Chris Basham      0
445        Jack O&#039;Connell      0
446             George Baldock      0
447               Enda Stevens      0
448             John Lundstram      0
449                 John Fleck      0
450             Oliver Norwood      0
451                     Wesley      0
452               Zack Steffen      0
453          Caoimhin Kelleher      0
454      Daniel N&#039;Lundulu      0
455              Billy Gilmour      0
456          Matthew Longstaff      0
457          Marvelous Nakamba      0
458                Eric Garcia      0
459           Brandon Williams      0
460             Niels Nkounkou      0
461         Amad Diallo Traore      0
462             Anthony Gordon      0
463               Scott Carson      0
464              Owen Otasowie      0
465              Neco Williams      0
466            Japhet Tanganga      0
467          William Smallbone      0
468                 Oskar Buur      0
469              Jack Robinson      0
470             Josh Brownhill      0
471             Ki-Jana Hoever      0
472              João Virgínia      0
473                 Pablo Marí      0
474     Bailey Peacock-Farrell      0
475                Jake Vokins      0
476        Alexandre Jankewitz      0
477              Joel Mumbongo      0
478                Marek Rodák      0
479              Illan Meslier      0
480                Luke Ayling      0
481           Jamie Shackleton      0
482          Ian Poveda-Ocampo      0
483           Dara O&#039;Shea      0
484            Romaine Sawyers      0
485               Kyle Edwards      0
486                    Vitinha      0
487      Konstantinos Tsimikas      0
488               Matthew Cash      0
489                 Liam Delap      0
490             Conor Townsend      0
491                   Max Lowe      0
492                 Leif Davis      0
493           Antonee Robinson      0
494               Jacob Ramsey      0
495            Vladimir Coufal      0
496           Filip Krovinovic      0
497           Lewis Richardson      0
498              Rhys Williams      0
499             Robert Sánchez      0
500                Andi Zeqiri      0
501            Elliot Anderson      0
502              Theo Corbeanu      0
503              Niall Huggins      0
504          Antwoine Hackford      0
505                  Percy Tau      0
506                Reda Khadra      0
507                Caleb Watts      0
508           Allan Tchaptchet      0
509                Jakub Moder      0
510              Iliman Ndiaye      0
511         Thakgalo Leshabela      0
512              Dane Scarlett      0
513         Carney Chukwuemeka      0
514            Shola Shoretire      0
515             Sidnei Tavares      0
516           Nathan Broadhead      0
517     Jaden Philogene-Bidace      0
518            Gaetano Berardi      0
519             Anthony Elanga      0
520                Femi Seriki      0
521            Tyrese Francois      0

In [29]:
import pandas as pd

pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 10)
pd.set_option('display.width', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

df = pd.read_csv('./epl-goalScorer(20-21).csv')

print(df[['player_name', 'goals', 'position', 'team_title', 'yellow_cards']])

                player_name  goals position         team_title  yellow_cards
0                Harry Kane     23        F          Tottenham             1
1             Mohamed Salah     22    F M S          Liverpool             0
2           Bruno Fernandes     18      M S  Manchester United             6
3             Son Heung-Min     17    F M S          Tottenham             0
4           Patrick Bamford     17      F S              Leeds             3
..                      ...    ...      ...                ...           ...
517  Jaden Philogene-Bidace      0        S        Aston Villa             0
518         Gaetano Berardi      0      D S              Leeds             0
519          Anthony Elanga      0        M  Manchester United             0
520             Femi Seriki      0        S   Sheffield United             0
521         Tyrese Francois      0        S             Fulham             0

[522 rows x 5 columns]

In [22]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\nPemain Liverpool:\n", df[df['team_title'] == 'Liverpool'][['player_name', 'team_title']])

Pemain Liverpool:
                  player_name team_title
1              Mohamed Salah  Liverpool
16                Sadio Mané  Liverpool
26           Roberto Firmino  Liverpool
30                Diogo Jota  Liverpool
116      Georginio Wijnaldum  Liverpool
130   Trent Alexander-Arnold  Liverpool
161         Thiago Alcántara  Liverpool
162               Joel Matip  Liverpool
172         Jordan Henderson  Liverpool
187          Virgil van Dijk  Liverpool
192  Alex Oxlade-Chamberlain  Liverpool
198                  Alisson  Liverpool
204         Andrew Robertson  Liverpool
226             Curtis Jones  Liverpool
251       Nathaniel Phillips  Liverpool
272             Divock Origi  Liverpool
274             James Milner  Liverpool
278                   Adrián  Liverpool
330          Xherdan Shaqiri  Liverpool
335             Joseph Gomez  Liverpool
375                  Fabinho  Liverpool
384               Naby Keita  Liverpool
436               Ozan Kabak  Liverpool
453        Caoimhin Kelleher  Liverpool
465            Neco Williams  Liverpool
487    Konstantinos Tsimikas  Liverpool
498            Rhys Williams  Liverpool

In [23]:
import pandas as pd
df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\nPemain Arsenal:\n", df[df['team_title'] == 'Arsenal'][['player_name', 'team_title']])

Pemain Arsenal:
                    player_name team_title
9          Alexandre Lacazette    Arsenal
19   Pierre-Emerick Aubameyang    Arsenal
36                Nicolas Pepe    Arsenal
65                 Bukayo Saka    Arsenal
140                    Gabriel    Arsenal
146              Eddie Nketiah    Arsenal
149           Emile Smith-Rowe    Arsenal
152         Gabriel Martinelli    Arsenal
160               Granit Xhaka    Arsenal
164            Héctor Bellerín    Arsenal
165             Mohamed Elneny    Arsenal
180                    Willian    Arsenal
203                 David Luiz    Arsenal
209            Martin Odegaard    Arsenal
248             Kieran Tierney    Arsenal
267                 Bernd Leno    Arsenal
269             Sead Kolasinac    Arsenal
275             Calum Chambers    Arsenal
322              Cédric Soares    Arsenal
348           Shkodran Mustafi    Arsenal
354                Rob Holding    Arsenal
366              Thomas Partey    Arsenal
369              Dani Ceballos    Arsenal
412               Reiss Nelson    Arsenal
423       Rúnar Alex Rúnarsson    Arsenal
473                 Pablo Marí    Arsenal

In [24]:
import pandas as pd
df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\n10 Kartu Kuning Terbanyak:\n", df[['player_name', 'yellow_cards']].sort_values(by='yellow_cards', ascending=False).head(10))

10 Kartu Kuning Terbanyak:
                player_name  yellow_cards
106            John McGinn            12
157        Conor Gallagher            11
125          Harry Maguire            11
259        Kalvin Phillips            10
110  Pierre-Emile Højbjerg             9
216       Luka Milivojevic             8
397           Isaac Hayden             8
218          Yves Bissouma             8
448         John Lundstram             8
399           Douglas Luiz             8

In [25]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')
print("\n10 Kartu Merah Terbanyak:\n", df[['player_name', 'red_cards']].sort_values(by='red_cards', ascending=False).head(10))

10 Kartu Merah Terbanyak:
              player_name  red_cards
61            Lewis Dunk          2
488         Matthew Cash          1
493     Antonee Robinson          1
21     Christian Benteke          1
18       Matheus Pereira          1
476  Alexandre Jankewitz          1
25          Tomas Soucek          1
443            John Egan          1
433            Ben White          1
421         Matt Doherty          1

In [26]:
import pandas as pd

df = pd.read_csv('./epl-goalScorer(20-21).csv')